<pre>
1	缺少参数
2	助教没有此操作的权限(teacher/teacher.php)
3	没有绑定教师的野生助教(teacher/teacher.php)
4	教师不属于此班级(teacher/teacher.php)
5	教师不属于此课程(teacher/teacher.php)
6	教师没有这个助教(teacher/teacher.php)
7	助教不属于此班级(teacher/teacher.php)
8	助教不属于此课程(teacher/teacher.php)
9	课程资料不属于此教师(teacher/teacher.php)
10	课程资料不属于此助教(teacher/teacher.php)
11	课程通知不属于此教师(teacher/teacher.php)
12	课程通知不属于此助教(teacher/teacher.php)
13	课程作业不属于此教师(teacher/teacher.php)
14	课程作业不属于此助教(teacher/teacher.php)


200 无法获取课程资料的根目录(teacher/course.php)


300 离线作业数据格式错误(teacher/homework/publish.php)
301 离线作业数据格式错误(teacher/homework/modify.php)
302 在线作业不提供下载(teacher/homework/result/download.php)
303 离线作业的分数不能大于100分(teacher/homework/result/checkAnswer.php)
304 批改分数高于设定的题目分数(teacher/homework/result/checkAnswer.php)
305 不存在的课程小组(teacher/homework/result/list.php)
306 获取课程小组失败(teacher/homework/result/list.php)
307 上传CSV文件失败(teacher/homework/result/exportCSV.php)
308 上传课程资料失败(course/material/upload.php)
309 获取助教权限失败(course/ta/getPermission.php)
310 已有的助教用户名(course/ta/addTA.php)
311 无法下载整个目录(course/material/download.php)

410	没有登录的教师或助教
411 需要JSON数据
412 没有登录的教师
413 没有登录的助教


502	数据库查询错误，查询助教拥有的权限(teacher/teacher.php)
503	数据库查询错误，查询助教属于的教师(teacher/teacher.php)
504	数据库查询错误，查询教师属于此班级(teacher/teacher.php)
505	数据库查询错误，查询教师属于此课程(teacher/teacher.php)
506	数据库查询错误，查询教师拥有的助教(teacher/teacher.php)
507	数据库查询错误，查询助教属于此班级(teacher/teacher.php)
508	数据库查询错误，查询助教属于此课程(teacher/teacher.php)
509	数据库查询错误，查询教师拥有此课程资料(teacher/teacher.php)
510	数据库查询错误，查询助教拥有此课程资料(teacher/teacher.php)
511	数据库查询错误，查询教师拥有此课程通知(teacher/teacher.php)
512	数据库查询错误，查询助教拥有此课程通知(teacher/teacher.php)
513	数据库查询错误，查询教师拥有此课程作业(teacher/teacher.php)
514	数据库查询错误，查询助教拥有此课程作业(teacher/teacher.php)
515	数据库查询错误，查询教师姓名(teacher/info.php)
516	数据库查询错误，查询助教姓名(teacher/info.php)
517	数据库查询错误，查询课程信息(teacher/info.php)
518 数据库查询错误，查询班级信息(teacher/class.php)
519 数据库查询错误，查询课程作业详情(teacher/homework/detail.php)
520 数据库操作错误，删除课程作业(teacher/homework/delete.php)
521 数据库操作错误，发布课程作业(teacher/homework/publish.php)
522 数据库查询错误，查询课程作业列表(teacher/homework/list.php)
523 数据库操作错误，修改课程作业(teacher/homework/modify.php)
524	数据库查询错误，查询作业类型(teacher/homework/result/download.php)
525 数据库查询错误，查询学生作业信息(teacher/homework/result/checkAnswer.php)
526 数据库操作错误，修改学生离线作业信息(teacher/homework/result/checkAnswer.php)
527 数据库操作错误，修改学生在线作业信息(teacher/homework/result/checkAnswer.php)
528 数据库查询错误，查询课程作业信息(teacher/homework/result/viewAnswer.php)
529 数据库查询错误，查询课程作业类型(teacher/homework/result/list.php)
530 数据库查询错误，查询学生作业列表(teacher/homework/result/list.php)
531 数据库操作错误，删除课程资料(course/material/delete.php)
532 数据库操作错误，添加课程资料子目录(course/material/addFolder.php)
533 数据库操作错误，添加课程资料(course/material/upload.php)
534 数据库操作错误，修改课程资料(course/material/rename.php)
535 数据库查询错误，查询课程资料根目录(course/material/list.php)
536 数据库查询错误，查询课程资料列表(course/material/list.php)
537 数据库操作错误，修改课程通知(course/notice/modify.php)
538 数据库查询错误，查询课程通知列表(course/notice/list.php)
539 数据库查询错误，查询课程通知详情(course/notice/detail.php)
540 数据库操作错误，删除课程通知(course/notice/delete.php)
541 数据库操作错误，发布课程通知(course/notice/publish.php)
542 数据库查询错误，查询助教权限(course/ta/getPermission.php)
543 数据库操作错误，删除助教(course/ta/delete.php)
544 数据库操作错误，添加助教(course/ta/addTA.php)
545 数据库操作错误，修改助教权限(course/ta/modifyPermission.php)
546 数据库操作错误，修改助教账号(course/ta/modify.php)
547 数据库查询错误，查询助教(course/ta/list.php)
548 数据库查询错误，查询助教权限(course/ta/getPermissionByTA.php)
549 数据库查询错误，查询课程资料信息(course/material/download.php)
550 数据库查询错误，查询作业资料信息(teacher/check.php)


601 XML读取错误，获取作业详情(teacher/homework/detail.php)
602 XML读取错误，获取作业详情(teacher/homework/result/checkAnswer.php)
603 XML读取错误，修改学生作业文件(teacher/homework/result/checkAnswer.php)
604 XML读取错误，获取作业详情(teacher/homework/viewAnswer.php)
605 XML读取错误，获取作业详情(teacher/homework/viewAnswer.php)
</pre>